export const LOAD_STEPS = 'LOAD_STEPS'
export const REVEAL_CARDS = 'REVEAL_CARDS'
export const AUTH_FIREBASE = 'AUTH_FIREBASE'
export const AUTH_SUCCEED = 'AUTH_SUCCEED'
export const AUTH_FAILED = 'AUTH_FAILED'
export const LOAD_USER = 'LOAD_USER'
export const SAVE_CARDS = 'SAVE_CARDS'